version: "3.7"
services:
  
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userdatabase
    ports:
      - "5433:5433"
  
  redis:
    container_name: redis
    image: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_vol:/var/lib/redis/data
  
  springapp:
    container_name: springapp
    build: .
    ports:
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/userdatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DB_HOST: db
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

volumes:
  redis_vol: